services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: my_database
    ports:
      - "5532:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      my_network:
        aliases:
          - db

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - my_network

  symfony:
    build: .
    container_name: symfony
    volumes:
      - ./symfony:/var/www/symfony
    depends_on:
      - postgres
    networks:
      - my_network
      - nginx_network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "9000:80"
    volumes:
      - ./symfony:/var/www/symfony
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - symfony
    networks:
      - nginx_network

networks:
  my_network:
    driver: bridge
  nginx_network:
    driver: bridge

volumes:
  postgres_data:
