controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    
api_medecins:
    path: /api/medecins
    controller: App\Controller\Api\MedecinController::getMedecins
    methods: GET
    
api_login_token:
    path: /api/login_token